#!/bin/bash
declare -ax display
declare -ax hand
declare -ax hold
declare -ax iteration
declare -ax library
declare -ax mchand
declare -ix dis
declare -ix flush
declare -ix four1
declare -ix four2
declare -ix index
declare -ix keep
declare -ix num1
declare -ix num2
declare -ix num3
declare -ix num4
declare -ix num5
declare -ix one
declare -ix pair1
declare -ix pair2
declare -ix pair3
declare -ix pair4
declare -ix repeat
declare -ix straight
declare -ix three
declare -ix three1
declare -ix three2
declare -ix three3
declare -ix two
declare -x card1
declare -x card2
declare -x card3
declare -x card4
declare -x card5
declare -x class1
declare -x class2
declare -x class3
declare -x class4
declare -x class5
declare -x flag
declare -x value
